SELECT NAME FROM SALESPERSON WHERE SALARY BETWEEN 30000 AND 40000;
SELECT NAME, SALARY FROM SALESPERSON ORDER BY SALARY DESC;
SELECT NAME, PHONE, DOB FROM SALESPERSON WHERE NAME LIKE 'A%;
SELECT AREA, COUNT (*) FROM SALESPERSON GROUP BY AREA;
SELECT DISTINCT(AREA) FROM SALESPERSON;
